language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build
  keep-history: true
  target-branch: gh-pages
  github-token: $github_token
  on:
    branch: master
env:
  global:
  - secure: bUrGlxygt0rt08HmxF02jIdf64wgxQZod9ws26f3+Tmc07dPgO4LhqQsq3ADYhlRC2Q2dAzTljrnqh2LI8pw0Lh4ZcZ1cr4AxCjoeEmZfA5Efko55Ddjuu+64P521Ffmp2ZVSp1td4iaMbxJOotfDJrlJNpFRxfupoaNqmcAZ/K9dErvu29O/dbVVaD/VXuLeovsBvqsYhEdmh3wexG8F9DE2OvBdeg0B2U1EWNSSBY/hTHxb1b6ARrmNl73O9dC6rppudGcmyAgx03SziM7Qt5aXp1x/HS3p2cRZUwvERRj9lfaSDgLfkhnl3FSa6LfGrlXZdyhRXEZHZFRs5rV0kS67pFYx+kXY2MAwoBHgivoqRmTGNETj7BqdoluE7TyIIfALsAN6yVcw8JSv6dNQomelvQGqnvJtbR6WUsuG9qlV27fHmkgPZVjC6GU5VBtQT+XoB8ZL6Qe+pt97MbvGCcaj2gowSMoHprfpgwmHDguhCEjFHpIURNNWyLpNUzAE9f3Q3klwdoY3++fwNrWTuVN2SaVeCON/XefBVRNgkYI5Cz1sqfHnT7FtMfca1/LSplrdFLFPvbl2CRYoZeiYT7KU8rfYJlPVM3WLaq1/06XaXYBiCaf3AcHyt2LSLH/bY68JMRZXB2PAyvzMJCpVp3S22SaUERexx5F5usrTpY=
