language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build
  keep-history: true
  target-branch: gh-pages
  github-token: "$github_token"
  on:
    branch: master
env:
  global:
  - secure: Fk/jk5p3umEnfnNGVZpDHHb4c24D+U7ftuxhgTgX9nfZPYR2ydK+lbV/cUjN21Pt77p6K9+7uCAYti0rZ6KQYRYVI5LP3V0mT5ojhIasxKmkDH58rK2NJK1gi3RUJBdjddadQx2duDevO7CE7wJorSOmNksDsVdKanEvoKD2Cf/q/xNtUSRCz6e9gOHQfMSJIyVm171UiB4UIHnqaqpBAlas2M9+TxEgpXtkMZBtra3D+UfkVy4ilc25zq9npLzmIZJfUJxbvpIiWVE3hCKPEXw6Xa3yvODumvBIJkiE2I/C9qyui21hrVFutb0AfU8rumRBEZV0D/p0IOtLTgXq1X/QRwULulLCfNU8DHgoExaLmoCrK8eg04gTYwDpEshHAWJwp5E5nm0folCWYEjU2RiZx3r3AgINfQXpRZLCnQPeu1c/uUxMWLKXZwMPj3iRYvu9YnW+M2GiTqAtcwCCus5Tij1s3TQH1V/clyLxYYUlOnMaMtHNTyK4fSTmFKgFDB9bqRoMfvKz1JGZ0dxGDCL5ceRvUx9eUYpijT5yd1jYcmRcvYByolJkTuk4scAxhCUMotw54YQD40r6Q1Fd2hHKU95p/VfRjRYKGvSqjrnUUoY+aBz77lEW/6way+BwQGwkUOBjyD/PlYUKQoiSZjZcTaYPvT5l8c07TxvDj/M=
