language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build
  target-branch: gh-pages
  keep-history: true
  github-token: $github_token
  on:
    branch: master
dd:
  secure: bz4Bw8H2U6coDlDXxSyzXKGeDXyxMyFFEdWJxmdyatXGGBu46NbNN30GuEjsoiLjdIJMatTXNmqY5BGrY9O99q+QB9KdxhtVX2KaDom7PsfGbAKVl34wTzQuIYPQhOaeIWqUHYrP+i9Bve50CuQz6ejqKE+jd2UyNkBVdjaTco/QxWX6P67F/AazUJAlrSj/Z4ylrA507avZrk1j0ypkSNg/y5PNN9alqmc8OLevWF+wLAdRMugb3/tCQ8oSy4inNKYQnmUY0NIt/py6P+NXBYyAdgICJk5DR1Sc8FDBrj4M93MysIm9Rq5XaNEke4feuQpiisK2KBj9zCeJRmm9Wxx8gdePODB0FF1nc1CJq2S80a2noHIQldMaVdZcfWj1syGohkt8/tj9jUQs6+49kLgjIyJFhAPHgYXyZOsxr37BjxCxRc+JbZfFsXhlQV1AWFK5uifXuQo34lHobLlDNHaq0RTweS+bBuoA8la5Y0rw8HWyE3kQ7pUaVG54sApRPtrniwIh4Vc/gap+7un9ODAnToj2ouduJkE3T86XqUo5ObADgDx9pAXpZdlG+U1af55U/25swUsa0XiWKst8O1411iTWre62PadMo8coPxAVN8xHJTKKIDHOCNZq44FL44gIsFCaYCjp9VBoQ3nMuk+YwPFN5grYEtjH8NBir0k=
